swagger: "2.0"
info:
  version: 1.2.1
  title: Factorio Blueprint Analyser
  description: Factorio Blueprint Analyser backend api
  contact:
    email: tomansion@yahoo.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /version:
    get:
      summary: Ping to check if the backend is running
      operationId: src.analysis.ping
      responses:
        200:
          description: The server is online

  # Analysis
  /analysis:
    post:
      summary: Start an analysis
      tags: [Analysis]
      operationId: src.analysis.start
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required: 
              - blueprint
              - parameters
            properties:
              blueprint:
                type: string
                description: The blueprint string or json string
              parameters:
                type: object
                properties:
                  inserterCapacityBonus:
                    type: integer
                    minimum: 0
                    maximum: 7
                    description: The inserters capacity bonus  
      responses:
        200:
          schema:
            type: object
          description: Blueprint analysis
        400:
          description: Invalid blueprint
